name: iBot IITM
title: iBot IITM
url: https://a-jacked-nerd.github.io/ibot_iitm_website/
# paginate: 5
# paginate_path: "/blog/page:num/"
plugins: 
- jekyll-paginate

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false

highlighter: rouge

exclude: ["/docs", vendor]
destination: "docs/"
